[workspace]
resolver = "2"
members = [
    "crates/modifile-core",
    "crates/modifile-cli",
    "crates/modifile-gui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Gamepro5/modifile"

[workspace.dependencies]
modifile-core = { path = "crates/modifile-core" }

# Release builds are tuned for a small, fast single binary. The whole point of
# this project is to not be a 300 MB Electron app.
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
